FROM python:3.13.5-slim-bookworm

WORKDIR /test

RUN apt-get update && apt-get install -y libpq-dev gcc && rm -rf /var/lib/apt/lists/*

COPY backend/requirements.txt .

COPY pytest.ini .

RUN python -m pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

RUN pip uninstall ecdsa -y || true

COPY backend backend

RUN cd backend/app/routers && rm -rf frontend.py || true

COPY tests tests

CMD ["pytest"]