"""empty message

Revision ID: 50ee17b16762
Revises: abc6a86f368a
Create Date: 2025-06-25 17:56:19.170365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50ee17b16762'
down_revision: Union[str, None] = 'abc6a86f368a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recur_tasks', sa.Column('user_task_id', sa.Integer(), nullable=False))
    op.add_column('recur_tasks', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'recur_tasks', ['id'])
    op.add_column('tasks', sa.Column('user_task_id', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'tasks', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'tasks', type_='unique')
    op.drop_column('tasks', 'is_completed')
    op.drop_column('tasks', 'user_task_id')
    op.drop_constraint(None, 'recur_tasks', type_='unique')
    op.drop_column('recur_tasks', 'is_completed')
    op.drop_column('recur_tasks', 'user_task_id')
    # ### end Alembic commands ###
