name: Task 1

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  
jobs:
  lint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_file_or_dir: 'docker-compose.yml'
          yamllint_strict: false
          yamllint_comment: true
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install pip
        run: python -m ensurepip --upgrade
      
      - name: Prepare dependencies
        run: pip install -r backend/requirements.txt
      
      - name: Create .env file
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD || 'example123'}}
          SECRET_KEY: ${{ secrets.SECRET_KEY || 'example_key23304163dswfd23bv123f7'}}
          REFRESH_SECRET_KEY: ${{ secrets.REFRESH_SECRET_KEY || 'example_key8asdg5asd02df'}}
          PGADMIN_PASSWORD: ${{ secrets.PGADMIN_PASSWORD || 'example123'}}
          TEST_DB_NAME: ${{ vars.TEST_DB_NAME || 'test_db' }}
          DB_NAME: ${{ vars.DB_NAME || 'main_db' }}
          USER: ${{ vars.USER || 'example' }}
          ALGORITHM: ${{ vars.ALGORITHM || 'HS256' }}
          REFRESH_ALGORITHM: ${{ vars.REFRESH_ALGORITHM || 'HS256' }}
          TOKEN_EXPIRE_MINUTES: ${{ vars.TOKEN_EXPIRE_MINUTES || 30 }}
          REFRESH_TOKEN_EXPIRE_MINUTES: ${{ vars.REFRESH_TOKEN_EXPIRE_MINUTES || 1440 }}
          PGADMIN_EMAIL: ${{ vars.PGADMIN_EMAIL || 'admin@example.com' }}
        run: |
          cat > .env << EOF
          TEST_DB_NAME=${TEST_DB_NAME}
          DB_NAME=${DB_NAME}
          DB_PASSWORD=${DB_PASSWORD}
          USER=${USER}
          TEST_DB_URL=postgresql://${USER}:${DB_PASSWORD}@${TEST_DB_NAME}:5432/${TEST_DB_NAME}
          DB_URL=postgresql://${USER}:${DB_PASSWORD}@${DB_NAME}:5432/${DB_NAME}
          SECRET_KEY=${SECRET_KEY}
          REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}
          ALGORITHM=${ALGORITHM}
          REFRESH_ALGORITHM=${REFRESH_ALGORITHM}
          TOKEN_EXPIRE_MINUTES=${TOKEN_EXPIRE_MINUTES}
          REFRESH_TOKEN_EXPIRE_MINUTES=${REFRESH_TOKEN_EXPIRE_MINUTES}
          PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
          PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
          EOF
      
      - name: Start app
        run: docker compose up -d
      
      - name: Wait for app to start 
        run: sleep 60

      - name: Run tests 
        run: docker compose run --rm tests 
        id: tests
      
      - name: Check test results
        if: steps.tests.outcome == 'failure'
        run: |
          echo "Tests failed"
          docker compose logs tests
          exit 1

  security:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r backend/requirements.txt
          pip uninstall ecdsa -y || true

      - uses: pypa/gh-action-pip-audit@v1.1.0

      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@v1

  build:
    needs: [lint, tests, security]
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: echo "App is building..."
